[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlpstorage"
version = "3.0.0"
description = "MLPerf Storage Benchmark Suite"
readme = "README.md"
authors = [
    {name = "MLCommons Storage Working Group", email = "storage-chairs@mlcommons.org"},
]
requires-python = ">=3.12,<3.13"
dependencies = [
  "dlio-benchmark @ git+https://github.com/argonne-lcf/dlio_benchmark.git@f794b65",
  "psutil>=5.9",
  "pyarrow",
]
license = {text = "Apache-2.0"}

[project.urls]
"Homepage" = "https://github.com/mlcommons/storage"
"Bug Tracker" = "https://github.com/mlcommons/storage/issues"

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.package-data]
"mlpstorage" = ["../configs/dlio/workload/*.yaml"]

[project.scripts]
mlpstorage = 'mlpstorage.main:main'

[tool.pdm]
distribution = true
