model: bert

framework: tensorflow

workflow:
  generate_data: False
  train: True
  debug: False
  checkpoint: True
 
dataset: 
  data_folder: data/bert
  format: tfrecord
  num_files_train: 500
  num_samples_per_file: 313532
  record_length: 2500
  file_prefix: part

train:
  computation_time: 0.968
  total_training_steps: 5000
 
reader:
  data_loader: tensorflow
  read_threads: 1
  computation_threads: 1
  transfer_size: 262144
  batch_size: 48
  file_shuffle: seed
  sample_shuffle: seed

checkpoint:
  checkpoint_folder: checkpoints/bert
  steps_between_checkpoints: 1250
  model_size: 4034713312
