model: 
  name: cosmoflow

framework: tensorflow

workflow:
 generate_data: False
 train: True

dataset:
 data_folder: data/cosmoflow
 num_files_train: 524288
 num_samples_per_file: 1
 record_length_bytes: 2828486
 record_length_bytes_stdev: 71311
 format: tfrecord

reader:
 data_loader: tensorflow
 read_threads: 4
 batch_size: 1
 file_shuffle: seed
 sample_shuffle: seed
 shuffle_size: 2
 
train: 
  epochs: 5
  computation_time: 0.00350

metric:
  au: 0.70
