model: 
  name: cosmoflow

framework: tensorflow

dataset:
 data_folder: data/cosmoflow
 num_files_train: 524288
 num_samples_per_file: 1
 record_length_bytes: 2828486
 record_length_bytes_stdev: 71311
 format: tfrecord
