model: 
  name: llama_70b
  type: transformer
  num_layers: 80
  model_datatype: fp16
  optimizer_datatype: fp32
  parallelism:
    tensor: 8
    pipeline: 1
    zero_stage: 3
  transformer: 
    vocab_size: 128256
    hidden_size: 8192
    ffn_hidden_size: 28672
    num_attention_heads: 128
    num_kv_heads: 8

framework: pytorch

workflow:
  generate_data: False
  train: False
  checkpoint: True

checkpoint:
  checkpoint_folder: checkpoints/llama_70b
  time_between_checkpoints: 5
  num_checkpoints_write: 10
  num_checkpoints_read: 10
  fsync: True