"""Rule 3.1.2 ``trainingRecalculateDatasetSize`` — exact ``ceil`` threshold.

PR #831 grandfathered datasets generated by mlpstorage < 3.0.43 (which
floored the datagen sizing) by lowering the validator's threshold to
``ceil - 1`` for the v3.0 round, with an explicit note to revert once
the round closed. The round is closed: Rules.md 3.1.2 says "fail the run
if the size recorded in the run's logfile doesn't exactly match the
recalculated value", so a dataset one file short of the ``ceil``
minimum must fail.

The fixture reuses the storage#669 reporter shape (15 hosts, 30
accelerators, unet3d record size). With ``num_files_train`` around
105_000 the steps-per-epoch term dominates and the minimum is exactly
105_000 files, so 104_999 sits precisely on the one-file boundary the
grandfather clause used to forgive.
"""

from mlpstorage_py.tests.test_issue_669_host_memory_aggregation import (
    _make_training_check,
    _reporter_summary_and_metadata,
)


def _run_with_num_files(tmp_path, num_files_train):
    summary, metadata = _reporter_summary_and_metadata()
    summary["num_files_train"] = num_files_train
    metadata["parameters"]["dataset"]["num_files_train"] = num_files_train
    check, log = _make_training_check(
        tmp_path, [(summary, metadata, "20260703_120000")]
    )
    return check.recalculate_dataset_size(), log


def test_3_1_2_exactly_at_ceil_minimum_passes(tmp_path):
    result, log = _run_with_num_files(tmp_path, 105_000)
    assert result is True, "a dataset exactly at the ceil minimum is valid"
    log.error.assert_not_called()


def test_3_1_2_one_file_short_of_ceil_minimum_fails(tmp_path):
    """Post-v3.0: the ceil-minus-one grandfather clause is gone."""
    result, log = _run_with_num_files(tmp_path, 104_999)
    assert result is False, (
        "3.1.2 must reject a dataset one file short of the recalculated "
        "ceil minimum; the v3.0 ceil-1 grandfather (PR #831) is retired"
    )
    log.error.assert_called_once()
    msg = log.error.call_args[0][0] % log.error.call_args[0][1:]
    assert "actual files 104999 < minimum required 105000" in msg, msg
