"""Task F — SUT (System Under Test) block population in reportgen output.

reportgen must emit the shared System-Under-Test columns (v3.0 results
table, `Results Table Structure.xlsx`) into results.{csv,json} for every
workload row, sourced from the row's `system-description.yaml`:

- ``sut_organization``  ← orgname (path)
- ``sut_name``          ← Hyperlink(text=solution.submission_name,
                                    href=<cat>/<org>/systems/<sys>.yaml)
- ``sut_description``    ← Hyperlink(text=solution.submission_name,
                                    href=<cat>/<org>/systems/<sys>.pdf)
- ``sut_rus``           ← system_under_test.total_rack_units

The remaining SUT cells are generated rather than hand-filled:
``sut_public_id`` (see test_reportgen_public_id.py) and the YAML-derived
``sut_type`` / ``sut_access_protocol`` / ``sut_availability`` /
``sut_integrated_client_storage`` / ``sut_usable_capacity_tib``
(see test_reportgen_sut_derived.py). This module's fixture YAML carries
neither, exercising the blank-degradation path.

Encoding (user-confirmed):
- ``.csv``  → hyperlink cell is an HTML anchor string
              ``<a href="...">text</a>``
- ``.json`` → hyperlink cell is a ``{"text": ..., "href": ...}`` object

Href base = repo-root-relative (Option A): ``<results-dir>`` is the
aggregated-submissions repo root, so ``closed/<org>/systems/<sys>.yaml``
is a valid relative URL.

Regression guard: the D-10 6-column prefix stays first and D-12 ``issues``
stays last — the ``sut_*`` columns are a body group between them.
"""

from __future__ import annotations

import csv
import json
import pathlib
import shutil
from argparse import Namespace

import pytest

from mlpstorage_py.report_generator import ReportGenerator

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
_FIXTURES_ROOT = _REPO_ROOT / "tests" / "fixtures" / "sample_results"

_SUBMISSION_NAME = "AcmeSysA"
_RACK_UNITS = 14

_ACME_YAML = f"""\
system_under_test:
  solution:
    submission_name: {_SUBMISSION_NAME}
  total_rack_units: {_RACK_UNITS}
"""


def _prepare_tree(tmp_path: pathlib.Path) -> pathlib.Path:
    """Copy the multi_orgname fixture and inject acme's system-description.yaml."""
    fixture_src = _FIXTURES_ROOT / "multi_orgname"
    assert fixture_src.is_dir(), f"expected fixture at {fixture_src}"
    dest = tmp_path / "repo_root"
    shutil.copytree(fixture_src, dest)
    systems_dir = dest / "closed" / "acme" / "systems"
    systems_dir.mkdir(parents=True, exist_ok=True)
    (systems_dir / "system-a.yaml").write_text(_ACME_YAML)
    return dest


def _run_reportgen(root: pathlib.Path) -> None:
    gen = ReportGenerator(str(root), args=Namespace(debug=False),
                          validate_structure=False)
    rc = gen.generate_reports()
    assert rc == 0, f"generate_reports returned {rc}"


def _acme_per_model_dir(root: pathlib.Path) -> pathlib.Path:
    return (root / "closed" / "acme" / "results" / "system-a"
            / "training" / "unet3d" / "run")


class TestSutBlockJson:
    def test_json_sut_columns_populated(self, tmp_path):
        root = _prepare_tree(tmp_path)
        _run_reportgen(root)
        rows = json.loads((_acme_per_model_dir(root) / "results.json").read_text())
        assert len(rows) == 1
        row = rows[0]

        assert row["Organization"] == "acme"
        assert row["RU's"] == _RACK_UNITS
        # Column-parity: Name shows the system name and links to the .yaml;
        # Description shows literal "PDF" and links to the .pdf.
        assert row["Name"] == {
            "text": "system-a",
            "href": "closed/acme/systems/system-a.yaml",
        }
        assert row["Description"] == {
            "text": "PDF",
            "href": "closed/acme/systems/system-a.pdf",
        }
        # Public ID is generated by reportgen (acme sorts first in this
        # fixture); see test_reportgen_public_id.py.
        assert row["Public ID"] == "v3.0-0001"
        # This fixture's YAML carries only submission_name + total_rack_units,
        # so the YAML-derived cells degrade to blank rather than raising;
        # see test_reportgen_sut_derived.py for the populated cases.
        for blank in ("Type", "Access Protocol", "Availability",
                      "Integrated Client Storage (TiB)",
                      "Usable Capacity (TiB)"):
            assert row[blank] == "", f"{blank} should be blank, got {row[blank]!r}"


class TestSutBlockCsv:
    def test_csv_hyperlinks_render_as_html_anchor(self, tmp_path):
        root = _prepare_tree(tmp_path)
        _run_reportgen(root)
        with open(_acme_per_model_dir(root) / "results.csv", newline="") as fh:
            rows = list(csv.DictReader(fh))
        assert len(rows) == 1
        row = rows[0]
        assert row["Name"] == (
            '<a href="closed/acme/systems/system-a.yaml">system-a</a>'
        )
        assert row["Description"] == (
            '<a href="closed/acme/systems/system-a.pdf">PDF</a>'
        )
        assert row["Organization"] == "acme"
        assert row["RU's"] == str(_RACK_UNITS)


_CODE_HASH = "0123456789abcdef0123456789abcdef"  # md5-tree-v2 32-hex
_CODE_DIR = "code-01234567"  # code-<first8>
_ACME_LEAF = ("closed/acme/results/system-a/training/unet3d/run/20260706_100000")


def _inject_code_pointer(root: pathlib.Path) -> None:
    leaf = root / _ACME_LEAF
    (leaf / ".mlps-code-image").write_text(f"md5-tree-v2:{_CODE_HASH}\n")


class TestSutCodeLogsLinks:
    """Task F-b: Code/Logs anchors resolved from the run's .mlps-code-image."""

    def test_json_code_logs_hyperlinks(self, tmp_path):
        # Column-parity: Code/Logs are per-workload. This is a training
        # fixture, so they land in the Training block.
        root = _prepare_tree(tmp_path)
        _inject_code_pointer(root)
        _run_reportgen(root)
        rows = json.loads((_acme_per_model_dir(root) / "results.json").read_text())
        row = rows[0]
        expected_href = f"closed/acme/{_CODE_DIR}/"
        assert row["Training - Code"] == {"text": "code", "href": expected_href}
        # Logs is a placeholder pointing at the same code-image dir for now.
        assert row["Training - Logs"] == {"text": "logs", "href": expected_href}

    def test_csv_code_logs_anchor(self, tmp_path):
        root = _prepare_tree(tmp_path)
        _inject_code_pointer(root)
        _run_reportgen(root)
        with open(_acme_per_model_dir(root) / "results.csv", newline="") as fh:
            row = next(csv.DictReader(fh))
        href = f"closed/acme/{_CODE_DIR}/"
        assert row["Training - Code"] == f'<a href="{href}">code</a>'
        assert row["Training - Logs"] == f'<a href="{href}">logs</a>'

    def test_missing_pointer_leaves_code_logs_blank(self, tmp_path):
        # No pointer injected → graceful blank, no crash.
        root = _prepare_tree(tmp_path)
        _run_reportgen(root)
        rows = json.loads((_acme_per_model_dir(root) / "results.json").read_text())
        row = rows[0]
        assert row["Training - Code"] == ""
        assert row["Training - Logs"] == ""


class TestSutBlockDoesNotBreakColumnInvariants:
    def test_fixed_schema_left_edge_and_sut_columns(self, tmp_path):
        from mlpstorage_py.report_generator import _FINAL_SCHEMA
        root = _prepare_tree(tmp_path)
        _run_reportgen(root)
        with open(_acme_per_model_dir(root) / "results.csv", newline="") as fh:
            header = next(csv.reader(fh))
        # Column-parity: the emitted header is EXACTLY the fixed schema.
        assert header == _FINAL_SCHEMA, f"header != fixed schema: {header}"
        # SUT columns present in the left-edge block; no machine-key
        # prefix or trailing issues column.
        for col in ("Organization", "Name", "Description", "RU's"):
            assert col in header
        for banned in ("orgname", "systemname", "benchmark_type", "issues"):
            assert banned not in header
