"""SUT block cells derived from ``systems/<name>.yaml`` (v3.0 column parity).

Five of the six formerly-manual System-Under-Test cells are now generated by
reportgen from the system-description YAML instead of being filled in by hand
after the fact:

===========================  ==================================================
Final column                 Source
===========================  ==================================================
``Type``                     ``solution.capabilities.simultaneous_write`` +
                             ``simultaneous_read`` (Shared / Failover), then
                             ``architecture.storage_location``, then
                             ``architecture.product_API``
``Access Protocol``          ``architecture.benchmark_API``: file -> POSIX,
                             object -> S3
``Availability``             ``solution.availability``, title-cased for display
``Usable Capacity (TiB)``    ``solution.usable_capacity_tib``
``Integrated Client          ``solution.int_client_store_tib`` (optional field;
Storage (TiB)``              blank when absent — nobody is expected to use it
                             in v3.0, the column survives for v2.0 parity)
===========================  ==================================================

The ``Type`` string is assembled exactly as specified:

    if (simultaneous_write && simultaneous_read) Type = 'Shared'
    else                                         Type = 'Failover'
    if (storage_location == 'remote_and_local')  Type += ' remote and local'
    else                                         Type += ' ' + storage_location
    Type += ' ' + product_API

Degradation contract: a system YAML that is missing, unreadable, or lacking
the source fields leaves the derived cells blank and logs a warning — it never
raises. reportgen must keep producing tables for a tree whose YAMLs have not
yet been backfilled with the new required fields. ``Type`` in particular is
blank when ANY of its four inputs is absent, rather than emitting a
half-built string like ``Shared remote None`` (user-confirmed).
"""

from __future__ import annotations

import json
import pathlib
import shutil
from argparse import Namespace

import pytest
import yaml

from mlpstorage_py.report_generator import ReportGenerator

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
_FIXTURES_ROOT = _REPO_ROOT / "tests" / "fixtures" / "sample_results"


def _system_yaml(
    *,
    storage_location: str = "remote",
    benchmark_API: str = "file",
    product_API: str = "file",
    simultaneous_write: bool = True,
    simultaneous_read: bool = True,
    usable_capacity_tib: int = 512,
    availability: str = "available",
    int_client_store_tib: int | None = None,
) -> dict:
    """A system-description dict carrying every field the SUT block reads."""
    solution = {
        "submission_name": "AcmeSysA",
        "friendly_description": "Acme test system",
        "architecture": {
            "storage_location": storage_location,
            "benchmark_API": benchmark_API,
            "product_API": product_API,
            "client_footprint": "open_source",
            "client_installation": "in_box",
        },
        "capabilities": {
            "multi_host": True,
            "simultaneous_write": simultaneous_write,
            "simultaneous_read": simultaneous_read,
            "remap_time_in_seconds": (
                0 if (simultaneous_write and simultaneous_read) else 30
            ),
        },
        "usable_capacity_tib": usable_capacity_tib,
        "availability": availability,
    }
    if int_client_store_tib is not None:
        solution["int_client_store_tib"] = int_client_store_tib
    return {"system_under_test": {"solution": solution, "total_rack_units": 14}}


def _prepare_tree(tmp_path: pathlib.Path, sys_yaml: dict) -> pathlib.Path:
    """Copy the multi_orgname fixture, writing *sys_yaml* as acme's system."""
    dest = tmp_path / "repo_root"
    shutil.copytree(_FIXTURES_ROOT / "multi_orgname", dest)
    systems_dir = dest / "closed" / "acme" / "systems"
    systems_dir.mkdir(parents=True, exist_ok=True)
    (systems_dir / "system-a.yaml").write_text(yaml.safe_dump(sys_yaml))
    return dest


def _acme_row(root: pathlib.Path) -> dict:
    gen = ReportGenerator(str(root), args=Namespace(debug=False),
                          validate_structure=False)
    rc = gen.generate_reports()
    assert rc == 0, f"generate_reports returned {rc}"
    per_model = (root / "closed" / "acme" / "results" / "system-a"
                 / "training" / "unet3d" / "run" / "results.json")
    rows = json.loads(per_model.read_text())
    assert len(rows) == 1
    return rows[0]


# --------------------------------------------------------------------------- #
# Type + Access Protocol                                                       #
# --------------------------------------------------------------------------- #

# Every (Type, Access Protocol) pair produced by the 115 system YAMLs in the
# v3.0 submission tree, plus two shapes the schema permits but nobody
# submitted (write-capable/read-restricted, and Failover remote_and_local).
_TYPE_CASES = [
    # storage_location, product_API, benchmark_API, s_write, s_read, Type, proto
    ("remote", "file", "file", True, True, "Shared remote file", "POSIX"),
    ("remote", "object", "object", True, True, "Shared remote object", "S3"),
    ("local", "file", "file", True, True, "Shared local file", "POSIX"),
    ("remote_and_local", "file", "file", True, True,
     "Shared remote and local file", "POSIX"),
    ("remote_and_local", "object", "object", True, True,
     "Shared remote and local object", "S3"),
    ("local", "block", "file", False, False, "Failover local block", "POSIX"),
    ("remote", "file", "file", False, True, "Failover remote file", "POSIX"),
    ("remote", "block", "file", False, True, "Failover remote block", "POSIX"),
    ("remote", "file", "file", True, False, "Failover remote file", "POSIX"),
    ("remote_and_local", "block", "file", False, False,
     "Failover remote and local block", "POSIX"),
]


class TestTypeAndAccessProtocol:
    @pytest.mark.parametrize(
        "loc,prod,bench,s_write,s_read,expected_type,expected_proto",
        _TYPE_CASES,
    )
    def test_derived_type_and_protocol(
        self, tmp_path, loc, prod, bench, s_write, s_read,
        expected_type, expected_proto,
    ):
        root = _prepare_tree(tmp_path, _system_yaml(
            storage_location=loc, product_API=prod, benchmark_API=bench,
            simultaneous_write=s_write, simultaneous_read=s_read,
        ))
        row = _acme_row(root)
        assert row["Type"] == expected_type
        assert row["Access Protocol"] == expected_proto

    def test_object_type_always_pairs_with_s3(self):
        """Any Type naming 'object' must carry Access Protocol 'S3'."""
        for _loc, _prod, _bench, _sw, _sr, exp_type, exp_proto in _TYPE_CASES:
            if "object" in exp_type:
                assert exp_proto == "S3", (
                    f"case {exp_type!r} pairs with {exp_proto!r}, not S3"
                )


# --------------------------------------------------------------------------- #
# Availability / capacities                                                    #
# --------------------------------------------------------------------------- #

class TestAvailability:
    @pytest.mark.parametrize("raw,displayed", [
        ("available", "Available"),
        ("preview", "Preview"),
        ("RDI", "RDI"),
    ])
    def test_availability_is_title_cased_for_display(
        self, tmp_path, raw, displayed
    ):
        root = _prepare_tree(tmp_path, _system_yaml(availability=raw))
        assert _acme_row(root)["Availability"] == displayed


class TestCapacities:
    def test_usable_capacity_passthrough(self, tmp_path):
        root = _prepare_tree(tmp_path, _system_yaml(usable_capacity_tib=1024))
        assert _acme_row(root)["Usable Capacity (TiB)"] == 1024

    def test_integrated_client_storage_present(self, tmp_path):
        root = _prepare_tree(tmp_path, _system_yaml(int_client_store_tib=64))
        assert _acme_row(root)["Integrated Client Storage (TiB)"] == 64

    def test_integrated_client_storage_absent_is_blank(self, tmp_path):
        """The optional field is expected to go unused in v3.0."""
        root = _prepare_tree(tmp_path, _system_yaml())
        assert _acme_row(root)["Integrated Client Storage (TiB)"] == ""


# --------------------------------------------------------------------------- #
# Degradation                                                                  #
# --------------------------------------------------------------------------- #

_DERIVED_COLUMNS = (
    "Type", "Access Protocol", "Availability",
    "Usable Capacity (TiB)", "Integrated Client Storage (TiB)",
)


class TestDegradesGracefully:
    def test_yaml_without_new_fields_leaves_cells_blank(self, tmp_path):
        """A not-yet-backfilled YAML must not break report generation."""
        root = _prepare_tree(tmp_path, {
            "system_under_test": {
                "solution": {"submission_name": "AcmeSysA"},
                "total_rack_units": 14,
            }
        })
        row = _acme_row(root)
        for col in _DERIVED_COLUMNS:
            assert row[col] == "", f"{col} should be blank, got {row[col]!r}"
        # The rest of the block is unaffected.
        assert row["Organization"] == "acme"
        assert row["RU's"] == 14

    def test_missing_system_yaml_leaves_cells_blank(self, tmp_path):
        dest = tmp_path / "repo_root"
        shutil.copytree(_FIXTURES_ROOT / "multi_orgname", dest)
        row = _acme_row(dest)  # no systems/ dir written at all
        for col in _DERIVED_COLUMNS:
            assert row[col] == ""

    def test_unreadable_yaml_leaves_cells_blank(self, tmp_path):
        dest = tmp_path / "repo_root"
        shutil.copytree(_FIXTURES_ROOT / "multi_orgname", dest)
        systems_dir = dest / "closed" / "acme" / "systems"
        systems_dir.mkdir(parents=True, exist_ok=True)
        (systems_dir / "system-a.yaml").write_text("{[ not: valid: yaml")
        row = _acme_row(dest)
        for col in _DERIVED_COLUMNS:
            assert row[col] == ""

    @pytest.mark.parametrize("dropped", [
        "storage_location", "product_API",
    ])
    def test_missing_architecture_field_blanks_type(self, tmp_path, dropped):
        """User-confirmed: blank Type when ANY architecture input is missing,
        never a half-built string like 'Shared remote None'."""
        sys_yaml = _system_yaml()
        del sys_yaml["system_under_test"]["solution"]["architecture"][dropped]
        root = _prepare_tree(tmp_path, sys_yaml)
        assert _acme_row(root)["Type"] == ""

    @pytest.mark.parametrize("dropped", [
        "simultaneous_write", "simultaneous_read",
    ])
    def test_missing_capability_field_blanks_type(self, tmp_path, dropped):
        sys_yaml = _system_yaml()
        del sys_yaml["system_under_test"]["solution"]["capabilities"][dropped]
        root = _prepare_tree(tmp_path, sys_yaml)
        assert _acme_row(root)["Type"] == ""

    def test_missing_benchmark_api_blanks_access_protocol(self, tmp_path):
        """Access Protocol has a single input; absent means blank, NOT the
        'S3' else-branch."""
        sys_yaml = _system_yaml()
        arch = sys_yaml["system_under_test"]["solution"]["architecture"]
        del arch["benchmark_API"]
        root = _prepare_tree(tmp_path, sys_yaml)
        assert _acme_row(root)["Access Protocol"] == ""

    def test_type_and_protocol_degrade_independently(self, tmp_path):
        """Dropping a Type input must not blank Access Protocol."""
        sys_yaml = _system_yaml()
        del sys_yaml["system_under_test"]["solution"]["architecture"]["product_API"]
        root = _prepare_tree(tmp_path, sys_yaml)
        row = _acme_row(root)
        assert row["Type"] == ""
        assert row["Access Protocol"] == "POSIX"
