database:
  host: 127.0.0.1
  port: 19530
  database: milvus
  max_receive_message_length: 514_983_574
  max_send_message_length: 514_983_574

dataset:
  collection_name: mlps_1m_1shards_1536dim_uniform
  num_vectors: 1_000_000
  dimension: 1536
  distribution: uniform
  batch_size: 10
  chunk_size: 100_000
  num_shards: 1
  vector_dtype: FLOAT_VECTOR

index:
  index_type: DISKANN
  metric_type: COSINE
  index_params:
    M: 64
    ef_construction: 200

workflow:
  compact: True